// Add or replace your own plant images in /public/plants/ and update the image paths below.
// Each category can contain as many plants as you want.

export const plantCategories = [
  "Temple",
  "Fruits",
  "Bonsai",
  "Garden",
  "Shurbs",
  "Medical Plants",
];

export const plantsByCategory = {


  Temple: [
    { name: "Jammi", image: "/temple/temple plnt 1 (Jammi).jpeg" },
    { name: "Malli", image: "/temple/temple plnt 2 (malli).jpeg" },
    { name: "Naagakesari", image: "/temple/temple plnt 3 (Naagakesari).jpeg" },
    { name: "Thelajiledu", image: "/temple/temple plnt 4 (Thelajiledu).jpeg" },
    { name: "Ravi", image: "/temple/temple plnt 5 (ravi).jpeg" },
    { name: "DANIMA", image: "/temple/temple plnt 7 (DANIMA).jpeg" },
    { name: "PANASA", image: "/temple/temple plnt 8 (PANASA).jpeg" },
    { name: "VEPA", image: "/temple/temple plnt 9 (VEPA).jpeg" },
    { name: "MAREDU", image: "/temple/temple plnt 11 (MAREDU).jpeg" },
    { name: "Moodhiga", image: "/temple/temple plnt 13 (Moodhiga).jpeg" },
    { name: "Marri", image: "/temple/temple plnt 14 (Marri).jpeg" },
    { name: "Templetra", image: "/temple/temple plnt 15 (templetra).jpeg" },
    { name: "Kariveeru", image: "/temple/temple plnt 16 (kariveeru).jpeg" },
    { name: "Vishnukrantham", image: "/temple/temple plnt 17 (Vishnukrantham).jpeg" },
    { name: "Usiri", image: "/temple/temple plnt 18 (usiri).jpeg" },
    { name: "Juvvi", image: "/temple/temple plnt 19 (juvvi).jpeg" },
    { name: "Meedi", image: "/temple/temple plnt 20  (meedi).jpeg" },
    { name: "Neeredu", image: "/temple/temple plnt 22  (neeredu).jpeg" },
    { name: "Mamidi", image: "/temple/temple plnt 23  (mamidi).jpeg" },
    { name: "Keembu", image: "/temple/temple plnt 24  (keembu).jpeg" },
    { name: "Poogada", image: "/temple/templeL plnt 6 (POOGADA).jpeg" },
    { name: "Velaga", image: "/temple/templeplnt 12 (VELAGA).jpeg" },
  ],
  Fruits: [
    {name: "Dasari Mamidi", image: "/fruits/fruit  plnt 1 (DASARI MAMIDI) copy 2.jpg.jpeg" },
    {name: "Pedda Usiri", image: "/fruits/fruit  plnt 2 (PEDDA USIRI) copy.jpg.jpeg" },
    {name: "Aarati", image: "/fruits/fruit  plnt 3 (aarati) copy.jpg.jpeg" },
    {name: "Pampara Panasa", image: "/fruits/fruit  plnt 4 PAMPARA PANASA) copy.jpg.jpeg" },
    {name: "Jama Safeda", image: "/fruits/fruit  plnt 5(JAMA SAFEDA) copy.jpg.jpeg" },
    {name: "Dragon Fruit", image: "/fruits/dragon fruit.webp" },
    {name: "Suvarana Rekha Mamidi", image: "/fruits/fruit  plnt 11  suvarana rekha   MAMIDI copy.jpg.jpeg" },
    {name: "Cherry Hybrid", image: "/fruits/fruit  plnt 32 cherry hybrid copy.jpg.jpeg" },
    {name: "Blimbi Usiri", image: "/fruits/fruit  plnt 33 blimbi usiri copy.jpg.jpeg" },
    {name: "Seetha Palam", image: "/fruits/fruit  plnt 36 seetha palam copy.jpg.jpeg" },
    {name: "Pachikayya Giney", image: "/fruits/fruit  plnt 39  pachikayya giney copy.jpg.jpeg" },
    {name: "Narinja Kobbari", image: "/fruits/fruit  plnt 41 narinja kobbari copy.jpg.jpeg" },
    {name: "Aapil Beer", image: "/fruits/fruit  plnt 42 aapil beer copy.jpg.jpeg" },
    {name: "Anjeer", image: "/fruits/fruit  plnt 45 anjeer copy.jpg.jpeg" },
    {name: "Panasa", image: "/fruits/fruit  plnt 47 panasa copy.jpg.jpeg" },
    {name: "Jeedi Mamidi", image: "/fruits/fruit  plnt 49 JEEDI MAMIDI copy.jpg.jpeg" },
    {name: "Vakkayi", image: "/fruits/fruit  plnt 51  vakkayi copy.jpg.jpeg" },
    {name: "vanga Mamidi", image: "/fruits/fruit  plnt 55 vanga mamidi copy.jpg.jpeg" },
    {name: "Seema Chinthakaya", image: "/fruits/fruit  plnt 60 seema chinthakaya copy.jpg.jpeg" },
    {name: "Star Fruit", image: "/fruits/fruit  plnt 61 star fruit copy.jpg.jpeg" },
    {name: "Tiyya Nimmakaya", image: "/fruits/fruit  plnt 62 tiyya nimmakaya copy.jpg.jpeg" },
    {name: "Red Lemon", image: "/fruits/fruit  plnt 67 red lemon copy.jpg.jpeg" },
    {name: "Staw berry", image: "/fruits/fruit  plnt 69 staw berry copy.jpg.jpeg" },
    {name: "Karjuram", image: "/fruits/fruit  plnt 73 karjuram copy.jpg.jpeg" },
    {name: "Sada Panasa", image: "/fruits/fruit  plnt 78 sada panasa copy.jpg.jpeg" },
    {name: "Vitanam Panasa", image: "/fruits/fruit  plnt 79 vitanam panasa copy.jpg.jpeg" },
    {name: "Sapota", image: "/fruits/fruit  plnt 80 cricket ball sapota copy.jpg.jpeg" },
  ],
  Bonsai: [
    {name: "Bonsai 1", image: "/bonsai/unnamed.webp" },
    {name: "Bonsai 2", image: "/bonsai/unnamed (1).webp" },
    {name: "Bonsai 3", image: "/bonsai/unnamed (2).webp" },
    {name: "Bonsai 4", image: "/bonsai/unnamed (3).webp" },
    {name: "Bonsai 5", image: "/bonsai/unnamed (4).webp" },
    {name: "Bonsai 6", image: "/bonsai/unnamed (5).webp" },
    {name: "Bonsai 7", image: "/bonsai/unnamed (6).webp" },
    {name: "Bonsai 8", image: "/bonsai/unnamed (7).webp" },
    {name: "Bonsai 9", image: "/bonsai/unnamed (8).webp" },
    {name: "Bonsai 10", image: "/bonsai/unnamed (9).webp" },
    {name: "Bonsai 11", image: "/bonsai/unnamed (10).webp" },
    {name: "Bonsai 12", image: "/bonsai/unnamed (11).webp" },
    {name: "Bonsai 13", image: "/bonsai/unnamed (12).webp" },
    {name: "Bonsai 14", image: "/bonsai/unnamed (13).webp" },
    {name: "Bonsai 15", image: "/bonsai/unnamed (14).webp" },
    {name: "Bonsai 16", image: "/bonsai/unnamed (15).webp" },
    {name: "Bonsai 17", image: "/bonsai/unnamed (16).webp" },
    {name: "Bonsai 18", image: "/bonsai/unnamed (17).webp" },
    {name: "Bonsai 19", image: "/bonsai/unnamed (18).webp" },
    {name: "Bonsai 20", image: "/bonsai/unnamed (19).webp" },
  ],
  Garden: [
    { image: "/garden/unnamed.webp" },
    { image: "/garden/unnamed (1).webp" },
    { image: "/garden/unnamed (2).webp" },
    { image: "/garden/unnamed (3).webp" },
    { image: "/garden/unnamed (4).webp" },
    { image: "/garden/unnamed (5).webp" },
    { image: "/garden/unnamed (6).webp" },
    { image: "/garden/unnamed (7).webp" },
    { image: "/garden/unnamed (8).webp" },
    { image: "/garden/unnamed (9).webp" },
    { image: "/garden/unnamed (10).webp" },
    { image: "/garden/unnamed (11).webp" },
    { image: "/garden/unnamed (12).webp" },
    { image: "/garden/unnamed (13).webp" },
    { image: "/garden/unnamed (14).webp" },
    { image: "/garden/unnamed (15).webp" },
    { image: "/garden/unnamed (16).webp" },
    { image: "/garden/unnamed (17).webp" },
    { image: "/garden/unnamed (18).webp" },
    { image: "/garden/unnamed (19).webp" },
  ],
  Shurbs: [
    {name: "Mini Ixora Varieties", image: "/shurbs/shurb 1 (Mini ixora varieties).jpeg" },
    {name: "Amazon Blue Talls", image: "/shurbs/shurb 2 (Amazon blue talls).jpeg" },
    {name: "Tecoma Purples", image: "/shurbs/shurb 3 (Tecoma purples).jpeg" },
    {name: "Tecoma Tecoma Yellow", image: "/shurbs/shurb 4 (Tecoma Tecoma yellow).jpeg" },
    {name: "Canna Yellow", image: "/shurbs/shurb 5 (Canna yellow).jpeg" },
    {name: "Rhoeo Tricolor Blue ", image: "/shurbs/shurb 6 (Rhoeo tricolor blue).jpeg" },
    {name: "Rhoeo Tricolor Red)", image: "/shurbs/shurb 7 (Rhoeo tricolor red).jpeg" },
    {name: "Amazon Blue Dwarf", image: "/shurbs/shurb 8 (amazon blue dwarf ).jpeg" },
    {name: "Tecoma Orangeo", image: "/shurbs/shurb 9 Tecoma orangeo.jpeg" },
    {name: "Snow Bus White", image: "/shurbs/shurb 10 snow bus white.jpeg" },
    {name: "Exocessia Try Color", image: "/shurbs/shurb 11 exocessia try color.jpeg" },
    {name: "Loropetalum Red", image: "/shurbs/shurb 12 Loropetalum red.jpeg" },
    {name: "Cassia Biflora Yellow", image: "/shurbs/shurb 13 Cassia biflora yellow.jpeg" },
    {name: "Crinum Lily Black", image: "/shurbs/shurb 14 Crinum lily black.jpeg" },
    {name: "Crinum Lily White", image: "/shurbs/shurb 15 Crinum lily white.jpeg" },
    {name: "Rasselia Verities", image: "/shurbs/shurb 16 Rasselia verities.jpeg" },
    {name: "Acalypha Green", image: "/shurbs/shurb 17 Acalypha green.jpeg" },
    {name: "Acalypha Red", image: "/shurbs/shurb 18  Acalypha red.jpeg" },
    {name: "Acalypha New Red", image: "/shurbs/shurb 19  Acalypha new red.jpeg" },
    {name: "Acalypha Hispida", image: "/shurbs/shurb 20  Acalypha hispida.jpeg" },
    {name: "Golden Durantha", image: "/shurbs/shurb 21  Golden durantha.jpeg" },
    {name: "Aralia Gold", image: "/shurbs/shurb 22 aralia  gold.jpeg" },
    {name: "Canna Red", image: "/shurbs/shurb 23 canna red.jpeg" },
    {name: "Canna Verigated", image: "/shurbs/shurb 24Canna verigated.jpeg" },
    {name: "Canna Black", image: "/shurbs/shurb 25 Canna black copy.jpeg" },
    {name: "Canna Indica", image: "/shurbs/shurb 26 Canna indica.jpeg" },
    {name: "Dracaena Mahatma", image: "/shurbs/shurb 27 Dracaena mahatma.jpeg" },
    {name: "Dracaena Colorama Red", image: "/shurbs/shurb 28 Dracaena colorama red.jpeg" },
    {name: "Dracaena Colorama White", image: "/shurbs/shurb 29 Dracaena colorama white.jpeg" },
    {name: "Croton Baby", image: "/shurbs/shurb 30  croton baby.jpeg" },
  ],
  "Medical Plants": [
    {name: "Mint", image: "/Medican/MEDICAL plnt 1 (MINT) copy.jpg.jpeg" },
    {name: "Vaamu", image: "/Medican/MEDICAL plnt 2 (vaamu) copy.jpg.jpeg" },
    {name: "Guruvindha", image: "/Medican/MEDICAL plnt 3 (Guruvindha) copy.jpg.jpeg" },
    {name: "Maasipatri", image: "/Medican/MEDICAL plnt 4 (Maasipatri) copy.jpg.jpeg" },
    {name: "Alovera", image: "/Medican/MEDICAL plnt 5 (alovera) copy.jpg.jpeg" },
    {name: "Tulasi", image: "/Medican/MEDICAL plnt 6 (tulasi) copy.jpg.jpeg" },
    {name: "Sarswathi", image: "/Medican/MEDICAL plnt 7 (sarswathi ) copy.jpg.jpeg" },
    {name: "Vatti Veela", image: "/Medican/MEDICAL plnt 10 (vatti veela) copy.jpg.jpeg" },
    {name: "Vasa", image: "/Medican/MEDICAL plnt 11 (vasa) copy 2.jpg.jpeg" },
    {name: "Nalla Isara", image: "/Medican/MEDICAL plnt 12 (nalla isara) copy.jpg.jpeg" },
    {name: "Pippalu", image: "/Medican/MEDICAL plnt 13 (pippalu copy 2.jpg.jpeg" },
    {name: "Podapatri", image: "/Medican/MEDICAL plnt 14 (podapatri) copy.jpg.jpeg" },
    {name: "Ranappala", image: "/Medican/MEDICAL plnt 16 (ranappala) copy.jpg.jpeg" },
    {name: "Sathavari", image: "/Medican/MEDICAL plnt 17 (sathavari) copy.jpg.jpeg" },
    {name: "Dhumparastram", image: "/Medican/MEDICAL plnt 18 (Dhumparastram) copy 2.jpg.jpeg" },
    {name: "Vavili", image: "/Medican/MEDICAL plnt 19 (vavili) copy.jpg.jpeg" },
    {name: "Rose merri", image: "/Medican/MEDICAL plnt 20 (rose merri ) copy.jpg.jpeg" },
    {name: "Enguva", image: "/Medican/MEDICAL plnt 21 (enguva) copy.jpg.jpeg" },
    {name: "Sindhuram", image: "/Medican/MEDICAL plnt 22  (sindhuram ) copy.jpg.jpeg" },
    {name: "Aswagandham", image: "/Medican/MEDICAL plnt 23  (aswagandham) copy.jpg.jpeg" },
    {name: "Insulin", image: "/Medican/MEDICAL plnt 24 (insulin) copy.jpg.jpeg" },
  ],
};
