// Add or replace your own plant images in /public/plants/ and update the image paths below.
// Each category can contain as many plants as you want.

export const plantCategories = [
  "Indoor",
  "Outdoor",
  "Flower",
  "Fruits",
  "Bonsai",
  "Garden",
  "Water Plants",
  "Low Maintenance Plants",
];

export const plantsByCategory = {
  Indoor: [
    { image: "/indoor plants/1-576x1024.webp" },
    { image: "/indoor plants/6b772c07-7774-4aef-a676-65d712cae748.jpeg" },
    { image: "/indoor plants/2024_Novemeber_Ecom_FloridaPlants-099.webp" },
    { image: "/indoor plants/1719282944-Dracaena-Golden-Heart-Main-scaled.avif" },
    { image: "/indoor plants/ChatGPT_Image_Dec_17_2025_12_42_28_PM.webp" },
    { image: "/indoor plants/coin_plant_1724763542_f0d8fd69_progressive.jpg" },
    { image: "/indoor plants/difficult-house-plant-croton-c70940d3ff2e47baa26983ffb9a4d58c.jpg" },
    { image: "/indoor plants/GettyImages-490131664-783cf3ba7ed24a9c9b5c8a7f29be1932.jpg" },
    { image: "/indoor plants/gettyimages-968405046-2000-eb0b2477f2874a58b2ec3107a29b24bf.jpg" },
    { image: "/indoor plants/il_fullxfull.7771478067_humw.webp" },
    { image: "/indoor plants/images.jpg" },
    { image: "/indoor plants/living-lace-victoria-bird-s-nest-fern-asplenium-antiquum-proven-winners_18891.jpg" },
    { image: "/indoor plants/plant_indian-basil.webp" },
    { image: "/indoor plants/revitalize_your_bedroom_space_54ezz.jpg" },
    { image: "/indoor plants/sam-galli-kVuW2Y40q1c-unsplash.webp" },
    { image: "/indoor plants/spider-plant.jpg.webp" },
    { image: "/indoor plants/shutterstock_1023339421-2048x1443.jpg" },
    { image: "/indoor plants/shutterstock_1464193490.jpg" },
    { image: "/indoor plants/the-sill-alocasia-tiny-dancer-medium-grant-cream-variant-67645543c9f48.avif" },
    { image: "/indoor plants/ugaoo_transform-this-image-img1_dtfHlihXSL.webp" },
    
  ],
  Outdoor: [
    { image: "/outdoor plants/0A20EC67-334A-4345-AB4A-D9964B5D20E3.webp" },
    { image: "/outdoor plants/4_clivia_13178_3_600.jpg" },
    { image: "/outdoor plants/1159603997_d596ea7b70.jpg" },
    { image: "/outdoor plants/dracaena-shutterstock_1403390915.jpg" },
    { image: "/outdoor plants/ficus-black.jpg" },
    { image: "/outdoor plants/Furcraea_Foetida_Mediopicta_-1.webp" },
    { image: "/outdoor plants/images (1).jpg" },
    { image: "/outdoor plants/images (2).jpg" },
    { image: "/outdoor plants/images (3).jpg" },
    { image: "/outdoor plants/images (4).jpg" },
    { image: "/outdoor plants/images.jpg" },
    { image: "/outdoor plants/IMG_5332_07cd16bd-b8e5-4430-a2cb-82f5da7118ee.webp" },
    { image: "/outdoor plants/Mammy-Red-is-known-for-its-colorful-foliage.jpg" },
    { image: "/outdoor plants/montana-aureomarginata-hosta-7564b73f-fe1c98587d424ae3aac31e5c882a2731.jpg" },
    { image: "/outdoor plants/nurserylive-air-purifier-money-plant_512x512.webp" },
    { image: "/outdoor plants/oxalis_2b58de46-06f6-4219-93ca-3e80a9a294aa.webp" },
    { image: "/outdoor plants/photo-1780867657408-2a011a64a3fa.avif" },
    { image: "/outdoor plants/Plants-for-Home-Garden-08-576x1024.jpg" },
    { image: "/outdoor plants/outdoor plant.jpg"},
    { image: "/outdoor plants/WhatsAppImage2026-06-02at15.52.20_2.jpg"},
  ],
  Flower: [
    { image: "/flowers/best-annual-flowers-sunflowers-1521752647.avif" },
    { image: "/flowers/clivia.jpg" },
    { image: "/flowers/image.webp" },
    { image: "/flowers/photo-1686454116831-05e1bbe04ee7.avif" },
    { image: "/flowers/unnamed (1).webp" },
    { image: "/flowers/unnamed (2).webp" },
    { image: "/flowers/unnamed (3).webp" },
    { image: "/flowers/unnamed (4).webp" },
    { image: "/flowers/unnamed (5).webp" },
    { image: "/flowers/unnamed (6).webp" },
    { image: "/flowers/unnamed (7).webp" },
    { image: "/flowers/unnamed (8).webp" },
    { image: "/flowers/unnamed (9).webp" },
    { image: "/flowers/unnamed (10).webp" },
    { image: "/flowers/unnamed (11).webp" },
    { image: "/flowers/unnamed (12).webp" },
    { image: "/flowers/unnamed (13).webp" },
    { image: "/flowers/unnamed (14).webp" },
    { image: "/flowers/unnamed.webp" },
    { image: "/flowers/Untitled-design-2023-08-19T162005.734.webp" },
  ],
  Fruits: [
    { image: "/fruits/amlla.jpg" },
    { image: "/fruits/Banana tree.webp" },
    { image: "/fruits/cherry.webp" },
    { image: "/fruits/chew.jpg" },
    { image: "/fruits/d7fede888742ddacb69f0dcfd7253a0e.jpg" },
    { image: "/fruits/dragon fruit.jpg" },
    { image: "/fruits/fruit.jpg" },
    { image: "/fruits/mango.jpg" },
    { image: "/fruits/neredu.jpg" },
    { image: "/fruits/orange.jpg" },
    { image: "/fruits/promognt.jpg" },
    { image: "/fruits/sapota.jpg" },
    { image: "/fruits/some fruit.jpg" },
    { image: "/fruits/star fruit.jpg" },
    { image: "/fruits/water mellon.jpg" },
    { image: "/fruits/guava.jpg" },
    { image: "/fruits/pinna apple.jpg" },
  ],
  Bonsai: [
    { image: "/bonsai/unnamed.webp" },
    { image: "/bonsai/unnamed (1).webp" },
    { image: "/bonsai/unnamed (2).webp" },
    { image: "/bonsai/unnamed (3).webp" },
    { image: "/bonsai/unnamed (4).webp" },
    { image: "/bonsai/unnamed (5).webp" },
    { image: "/bonsai/unnamed (6).webp" },
    { image: "/bonsai/unnamed (7).webp" },
    { image: "/bonsai/unnamed (8).webp" },
    { image: "/bonsai/unnamed (9).webp" },
    { image: "/bonsai/unnamed (10).webp" },
    { image: "/bonsai/unnamed (11).webp" },
    { image: "/bonsai/unnamed (12).webp" },
    { image: "/bonsai/unnamed (13).webp" },
    { image: "/bonsai/unnamed (14).webp" },
    { image: "/bonsai/unnamed (15).webp" },
    { image: "/bonsai/unnamed (16).webp" },
    { image: "/bonsai/unnamed (17).webp" },
    { image: "/bonsai/unnamed (18).webp" },
    { image: "/bonsai/unnamed (19).webp" },
  ],
  Garden: [
    { image: "/garden/unnamed.webp" },
    { image: "/garden/unnamed (1).webp" },
    { image: "/garden/unnamed (2).webp" },
    { image: "/garden/unnamed (3).webp" },
    { image: "/garden/unnamed (4).webp" },
    { image: "/garden/unnamed (5).webp" },
    { image: "/garden/unnamed (6).webp" },
    { image: "/garden/unnamed (7).webp" },
    { image: "/garden/unnamed (8).webp" },
    { image: "/garden/unnamed (9).webp" },
    { image: "/garden/unnamed (10).webp" },
    { image: "/garden/unnamed (11).webp" },
    { image: "/garden/unnamed (12).webp" },
    { image: "/garden/unnamed (13).webp" },
    { image: "/garden/unnamed (14).webp" },
    { image: "/garden/unnamed (15).webp" },
    { image: "/garden/unnamed (16).webp" },
    { image: "/garden/unnamed (17).webp" },
    { image: "/garden/unnamed (18).webp" },
    { image: "/garden/unnamed (19).webp" },
  ],
  "Water Plants": [
    { image: "/water plants/unnamed.webp" },
    { image: "/water plants/unnamed (1).webp" },
    { image: "/water plants/unnamed (2).webp" },
    { image: "/water plants/un 3.jpg" },
    { image: "/water plants/un 4.jpg" },
    { image: "/water plants/un 5.jpg" },
    { image: "/water plants/un 6.jpg" },
    { image: "/water plants/un 7.jpg" },
    { image: "/water plants/un 8.jpg" },
    { image: "/water plants/un 9.jpg" },
    { image: "/water plants/un 10.jpg" },
    { image: "/water plants/un 11.jpg" },
    { image: "/water plants/un 12.jpg" },
    { image: "/water plants/un 13.jpg" },
    { image: "/water plants/un 14.jpg" },
    { image: "/water plants/un 20.jpg" },
    { image: "/water plants/un 16.jpg" },
    { image: "/water plants/un 17.jpg" },
    { image: "/water plants/un 18.jpg" },
    { image: "/water plants/un 19.jpg" },
  ],
  "Low Maintenance Plants": [
    { image: "/low mantnce plants/3.jpg" },
    { image: "/low mantnce plants/4.jpg" },
    { image: "/low mantnce plants/5.jpg" },
    { image: "/low mantnce plants/6.jpg" },
    { image: "/low mantnce plants/7.jpg" },
    { image: "/low mantnce plants/8.jpg" },
    { image: "/low mantnce plants/9.jpg" },
    { image: "/low mantnce plants/10.jpg" },
    { image: "/low mantnce plants/11.jpg" },
    { image: "/low mantnce plants/12.jpg" },
    { image: "/low mantnce plants/13.jpg" },
    { image: "/low mantnce plants/14.jpg" },
    { image: "/low mantnce plants/15.jpg" },
    { image: "/low mantnce plants/16.jpg" },
    { image: "/low mantnce plants/17.jpg" },
    { image: "/low mantnce plants/18.jpg" },
    { image: "/low mantnce plants/19.jpg" },
    { image: "/low mantnce plants/20.jpg" },
    { image: "/low mantnce plants/21.jpg" },
    { image: "/low mantnce plants/22.jpg" },
  ],
};
